jobs:
  - name: khranity
    path: /root/khranity
    token: "file:khranity.token"
    schedule: "0 1 * * 0,1,2,3,4,5,6"
    tz: "Europe/Moscow"
    cloud: yandex
    archiver: native
    ignore:
      - .git
      - build
      - logs
  - name: test
    path: /root/khranity
    token: "file:khranity.token"
    schedule: "0 1 * * 0,1,2,3,4,5,6"
    tz: "Europe/Moscow"
    cloud: selectel
    archiver: native
    ignore:
      - .git
      - node_modules
      - .next
      - logs

clouds:
  - name: selectel
    method: aws
    url: "https://s3.storage.selcloud.ru"
    region: "ru-1"
    bucket: backups
    access_id:  "file:selectelID.token"
    secret_key: "file:selectelKey.token"
  - name: yandex
    method: aws
    url: "https://storage.yandexcloud.net"
    region: "ru-central1"
    bucket: backups1
    access_id:  "file:yandexID.token"
    secret_key: "file:yandexKey.token"

setup:
  os: nix